package scanner

var HTMLTemplate = `<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>sharefinder report</title>
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">sharefinder</a>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
				<li>
					<a href="#identifiedHosts">Hosts</a>
				</li>
				<li>
					<a href="#Hosts">Shares</a>
				</li>
				<li>
					<a href="#identifiedFiles">Files</a>
				</li>
			</ul>
		</div>
	</nav>

	<div id="body">
		<div id="summary">
			<h1>SMB shares scan report</h1>
			</h2>sharefinder {{ .Version }}</h2>
			<code>{{ .ExecutedCommand }}</code>
			<p>{{ .TimeStart }} - {{ .TimeEnd }}</p>
		</div>
		
		<!-- Summary of identified hosts with version number, hostname, domain name, signing, SMBv1, number of shares -->
		<h2>Identified Hosts</h2>
		<div id="identifiedHosts">
			
			{{ range .Hosts }}

			{{ end }}
		</div>

		<!-- Detailed results for each identified host. -->
		<h2>Host Results</h2>
		<div id="Hosts">
			{{ range .Hosts }}
			<h3>{{ .IP }}</h3>
			<h4>Shares</h4>
			<table id="hostShares">
			<thead>

			</thead>
			{{ range .Shares }}
			
			{{ end }}
			</table>
			
			{{ end }}
		</div>

		<!-- List of identified files and directories -->
		<h2>Identified Files</h2>
		<div id="identifiedFiles">
			<table id="tableFiles">
			<thead>
				<th>Host</th>
				<th>Share</th>
				<th>Path</th>
				<th>Type</th>
				<th>Filename</th>
				<th>Size</th>
				<th>Last Modified</th>
			</thead>
			<tbody>
			{{ range .Hosts }}
			<tr>
				<td></td>
			</tr>
			{{ end }}
			</tbody>
			</table>
		</div>
	</div>

	<footer class="footer">
		<div class="container">
			<p>
				This report was generated by <a href="https://github.com/vflame6/sharefinder">sharefinder</a>.
				<br>
				Designed and built by Maksim Radaev (<a href="https://x.com/MaksimRadaev">@MaksimRadaev</a>).
				<br>
			</p>
		</div>
	</footer>
</body>

</html>`
